### ISSUE TITLE
Code block are invisible on edit

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms-site#38] opened 2019-10-09 13:34 UTC
Given I am on http://localhost:8000/docs/gatsby/manual-setup
When I click on inline `Edit` button
Then code blocks content is not displayed in the WYSIWYM editor

<img width="780" alt="tina-edit-markdown-code-blocks" src="https://user-images.githubusercontent.com/103008/66485847-c3fcad80-eaa9-11e9-8b60-c8d658eee833.png">

**Comment by kendallstrautman** [comment] 2019-11-11 17:18
Unable to reproduce. Closing for now.

**Closed by kendallstrautman** 2019-11-11 17:18 UTC
Labels: bug
