### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms-site#90] opened 2019-10-22 15:47 UTC
there are still a lot of improvements to be made to our documentaiton, but an FAQ page could resolve some common questions/confusion quickly.

possible topics:
- How is Tina different from a CMS?
- Can I use Tina with X? (where X is some SSG feature like MDX etc)
- can I create new posts using Tina?

**Comment by kendallstrautman** [comment] 2019-12-06 21:52
duplicate of #128

**Closed by kendallstrautman** 2019-12-06 21:52 UTC
Labels: enhancement
